// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX1oFm9xcjiFEsBdta3Qbk2g5yEwEtQxA',
    appId: '1:423183039157:web:338efd7cf76a9bf9331cfc',
    messagingSenderId: '423183039157',
    projectId: 'aski-8a0b5',
    authDomain: 'aski-8a0b5.firebaseapp.com',
    databaseURL: 'https://aski-8a0b5-default-rtdb.firebaseio.com',
    storageBucket: 'aski-8a0b5.appspot.com',
    measurementId: 'G-9BDQ68NLJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcmxq-kJR4LhwIp2wSwr6IOPH74uP7Ngs',
    appId: '1:423183039157:android:4ca902b905af3d57331cfc',
    messagingSenderId: '423183039157',
    projectId: 'aski-8a0b5',
    databaseURL: 'https://aski-8a0b5-default-rtdb.firebaseio.com',
    storageBucket: 'aski-8a0b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6eXt6Ot-hsPbaT9fIkIgiCKHv3vVqfRo',
    appId: '1:423183039157:ios:67c182b41f4845cc331cfc',
    messagingSenderId: '423183039157',
    projectId: 'aski-8a0b5',
    databaseURL: 'https://aski-8a0b5-default-rtdb.firebaseio.com',
    storageBucket: 'aski-8a0b5.appspot.com',
    iosClientId: '423183039157-pi4jp700073n6eks3nnl11m57ad4emcc.apps.googleusercontent.com',
    iosBundleId: 'com.blacklabelengineering.aski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6eXt6Ot-hsPbaT9fIkIgiCKHv3vVqfRo',
    appId: '1:423183039157:ios:0122c52fb0bd49e9331cfc',
    messagingSenderId: '423183039157',
    projectId: 'aski-8a0b5',
    databaseURL: 'https://aski-8a0b5-default-rtdb.firebaseio.com',
    storageBucket: 'aski-8a0b5.appspot.com',
    iosClientId: '423183039157-dc9lv2088abktl8ijc293a7dopvv4gne.apps.googleusercontent.com',
    iosBundleId: 'com.blacklabelengineering.aski.RunnerTests',
  );
}
